language: node_js
node_js:
 - "node"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y jq

install:
  # Download ngrok
  - curl -sO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  - unzip $PWD/ngrok-stable-linux-amd64.zip
  - chmod +x $PWD/ngrok

script:
  # Start our application
  - node hello.js &
  # Open ngrok tunnel
  - $PWD/ngrok authtoken $NGROK_TOKEN
  - $PWD/ngrok http 8000 > /dev/null &
  # Execute Ghost Inspector tests using the ngrok tunnel
  - curl 'http://localhost:4040/api/tunnels'
  - curl "https://api.ghostinspector.com/v1/suites/$GHOST_SUITE_ID/execute/?apiKey=$GHOST_API_KEY&startUrl=$(curl 'http://localhost:4040/api/tunnels' | jq -r '.tunnels[1].public_url')" > $PWD/ghostinspector.json
  # Exit with a fail status if any tests have failed
  - if [ $(grep -c '"passing":false' $PWD/ghostinspector.json) -ne 0 ]; then exit 1; fi
